import Head from 'next/head';
import Link from 'next/Link';
import { Container, Row, Col } from 'react-bootstrap';
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <Container fluid style={{height:'100vh',border:'1px solid red'}} 
      //className={styles.main}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row>
        <Col xs={12}>
        <Link href='/docs'>
          docs
        </Link>
        </Col>
        <Col xs={12}>
        <Link href='/product'>
          prod
        </Link>
        </Col>

      </Row>
    </Container>
  )
}
